services:
  app:
    image: node:18
    ports:
      - "${PORT}:${PORT}"
    container_name: evora-be
    working_dir : /app
    environment:
      MONGO_URI: ${URL_MONGODB_DEV}
    volumes:
      - ./:/app
    networks:
      - evora-networks
    depends_on:
      - mongo
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:latest
    container_name: evora_mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - evora_mongodata:/data/db
    networks:
      - evora-networks


volumes:
  evora_mongodata:

networks:
  evora-networks:
    driver: bridge